### PR TITLE
compliance: remove hide prayers

### PR DESCRIPTION
**Pull request by zeruth**
in compliance with "Reorders, moves, or resizes prayers or spells"

### CODE REVIEW

**Comment by xKylee** [comment]
I actually think this one is fine, seeing how you are allowed to hide attack options still....

**Comment by zeruth** [comment]
Hiding is resizing, its not fine.

**Comment by xKylee** [comment]
Wut

**Comment by zeruth** [comment]
I mean I guess it's all perspective, if RL or OSB have it, its fine I guess.

**Pull request closed without merging**
