### PR TITLE
party: fix websocket events not being posted

### LINKED ISSUE #2443: discord party pinging broken
**Describe the bug**
When in a party pinging doesn't ping/show

**To Reproduce**
Join discord party with other openosrs user.
Hold shift and you'll see you won't walk, but no pings are happening. 

**Expected behavior**
No pings show, despite not walking when pressing with shift held in.

**Screenshots**

**Environment (please complete the following information):**
windows 10

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

### PR DESCRIPTION
**Pull request by ThatGamerBlue**
Closes #2443
https://i.imgur.com/vJJordO.png

### CODE REVIEW

**Comment by Owain94** [comment]
https://github.com/open-osrs/runelite/pull/2191/files

This should be partially revert now i guess?

**Comment by ThatGamerBlue** [comment]
what in the name of ever loving fuck happened there

**Comment by Owain94** [comment]
Null pushed that in an attempt to fix the party plugin

**Comment by Dogyyblue** [comment]
<3 @Owain94

**Pull request merged**
