### PR TITLE
change: add features into the Ground Items Plugin

### PR DESCRIPTION
**Pull request by ProtoGrace**
Implement GE price sorting as well as right-click hidden items into Ground Items Plugin.

### CODE REVIEW

**Comment by wizar-d** [comment]
poger

**Comment by wizar-d** [comment]
not poger it failed...

**Comment by ProtoGrace** [comment]
will fix the styling and recommit 😱

**Comment by ProtoGrace** [comment]
Fixed the formatting issues after many attempts 🤣

**Comment by wizar-d** [comment]
POGER LETS GOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by zeruth** [comment]
What you should do is copy the plugin, make your changes, then externalize it and PR to the plugins repo. We should try to stay away from changes to built-in plugins where possible. Things like this will make upstreams difficult down the road.

**Comment by ProtoGrace** [comment]
Ah okay, Ill do that then.

**Pull request closed without merging**
