### PR TITLE
screenshotplugin: hide overlays on screenshot

### PR DESCRIPTION
**Pull request by stone-wall**
adds option to hide overlays on screenshot. 
plz squash, i didn't re-base before did this

### CODE REVIEW

**Comment by SRLJustin** [comment]
Once a screenshot has been taken, overlays are not re-added to the client

**Comment by stone-wall** [comment]
> Once a screenshot has been taken, overlays are not re-added to the client
> 
> Edit: logging in and out still wont re-add any overlay, a full client restart is currently required

@SRLJustin can you let me know which screenshot settings you were using/which overlays you had on? i haven't been able to replicate that problem. for me, when a sceenshots captured the overlays briefly disappear then reappear like this
image

**Comment by SRLJustin** [comment]
Settings: 
image

(reverted the PR so the config option is removed)

I was looting a chest at Olm

**Comment by SRLJustin** [comment]
Just tested this again, killed Vorkath, overlays removed but not re-added once the picture was taken (screenshot automatically taken by the client)

Pushing the Screenshot button also removes the overlays and doesn't re-add them (Agility shortcuts, inventory tags for example)

**Comment by xKylee** [comment]
@SRLJustin st0ne pushed a fix, can you re-test?ive been testing and cant reproduce

**Comment by xKylee** [comment]
@SRLJustin can you re-test with the latest changes please

**Comment by xKylee** [comment]
will need to RE-PR to https://github.com/open-osrs/plugins.

**Pull request closed without merging**
