### PR TITLE
Github Actions: upload artifact

### PR DESCRIPTION
**Pull request by pklite**
Also switches to JDK8. Can use this for nightly build, there are a few actions for deployment options like uploading as a Release, etc. Wasn't sure on which would be best to use

### CODE REVIEW

**Comment by pklite** [comment]
> Would it be possible to keep the CI intact and run nightlife’s with a cron once a day instead of every commit?
> 
> Like how the stale issues action is being ran
> 
> Also would it be possible to upload the artifact (client jar, api jar etc) and build a bootstrap.json so we can have a nightlies launcher instead of just a jar that needs to be downloaded every single commit?

for the cron, yeah definitely that's a good idea, ill push that to this branch. the bootstrapping and other artifact upload was what i was thinking too. pretty sure actions can be used to upload the artifacts to tuxfamily through shftp or ftp and we can just use that for the nightlies

**Comment by zeruth** [comment]
Why switch to JDK8? We are JDK 11 compliant, and our launcher includes JDK11. That's what we should be using.

**Comment by ThatGamerBlue** [comment]
Because most of our users are using 8, and backwards compat from 9 -> 8 is broken

**Comment by zeruth** [comment]
Well most of our users won't be downloading nightlies. People should conform to our project wide standards, not the other way around.

**Comment by Owain94** [comment]
I rather build a launcher for the nightlies otherwise users have to go to the website every single day to get an updated version while a launcher makes that way more user friendly.

Also that way we can have the improvements that come with java 11

**Comment by Ganom** [comment]
> 
> 
> I rather build a launcher for the nightlies otherwise users have to go to the website every single day to get an updated version while a launcher makes that way more user friendly.
> 
> Also that way we can have the improvements that come with java 11

Best option i feel would be a launcher arg, --nightly and you'll be directed to a nightly bootstrap.

**Comment by pklite** [comment]
> > I rather build a launcher for the nightlies otherwise users have to go to the website every single day to get an updated version while a launcher makes that way more user friendly.
> > Also that way we can have the improvements that come with java 11
> 
> Best option i feel would be a launcher arg, --nightly and you'll be directed to a nightly bootstrap.

yeah i think this would be better than having two different launchers

**Comment by Owain94** [comment]
I agree that would be way better

**Pull request closed without merging**
