### PR TITLE
varbits: add Ernest chicken lever

### PR DESCRIPTION
**Pull request by chadsisson**
Earnest the chicken

### CODE REVIEW

**Comment by chadsisson** [comment]
> Please fix your title.
> https://i.imgur.com/x6Amtd9.jpg

Hello, 

I'm not sure how to do this.

**Comment by Crystalknoct** [comment]
This https://i.imgur.com/OxJhud2.jpg should be "merge: upstream" for example
Title https://i.imgur.com/K4ljEI1.jpg needs to be the something like "Added: quest varbits" you can edit the title.

**Comment by chadsisson** [comment]
> This https://i.imgur.com/OxJhud2.jpg should be "merge: upstream" for example
> Title https://i.imgur.com/K4ljEI1.jpg needs to be the something like "Added: quest varbits" you can edit the title.

How is that?

**Comment by xKylee** [comment]
I got you.

**Pull request merged**
