### PR TITLE
events: add RunScriptEvent for cs2 logging

### PR DESCRIPTION
**Pull request by Ganom**

### CODE REVIEW

**Comment by Lucwousin** [comment]
This could probably do with a dev tools button like the menu actions thing

**Comment by Ganom** [comment]
> This could probably do with a dev tools button like the menu actions thing

True, but there is a lot of spam from things you may not want. That was the main reason i opted for an event rather than a logger.

The 3 examples i listed in the javadocs are ones that fire every client tick and make it essentially unreadable.

**Comment by Lucwousin** [comment]
I agree it's unreasonable to just log them all, but keep in mind that this event will still run every time a script runs, even if you've turned off your (quickly  (self)made) log plugin (tm) for the day.

Your current implementation also posts the (mutable) args array ref, before the script has ran. A bit of unlucky logging, and you accidentally modify one sending your entire client apeshit. That, or a quick array copy, but then you incur the cost of that again.

I feel like you instead should focus on when logging a script has a benefit rather than logging them all and picking what you need from that

**Comment by Ganom** [comment]
> I agree it's unreasonable to just log them all, but keep in mind that this event will still run every time a script runs, even if you've turned off your (quickly (self)made) log plugin (tm) for the day.

That is very true, would a hybrid work better here, ie: dev tool button that enables the event?

> Your current implementation also posts the (mutable) args array ref, before the script has ran. A bit of unlucky logging, and you accidentally modify one sending your entire client apeshit. That, or a quick array copy, but then you incur the cost of that again.

I did not even realize that, definitely need to do an array copy here. Thanks for bringing that up.

> I feel like you instead should focus on when logging a script has a benefit rather than logging them all and picking what you need from that

The main reason I made this was to just get a glimpse into whats happening in the client, so logging them all was the goal.

**Comment by Lucwousin** [comment]
(You're also not logging scripts invoked from other scripts)

onTimer is the spammy one 🤷‍♂ 
````
Object[] onLoad
Object[] onClick
Object[] onClickRepeat
Object[] onRelease
Object[] onHold
Object[] onMouseOver
Object[] onMouseRepeat
Object[] onMouseLeave
Object[] onDrag
Object[] onDragComplete
Object[] onTargetEnter
Object[] onTargetLeave
Object[] onVarTransmit
Object[] onInvTransmit
Object[] onStatTransmit
Object[] onTimer
Object[] onOp
Object[] onScroll
Object[] onChatTransmit
Object[] onKey
Object[] onFriendTransmit
Object[] onClanTransmit
Object[] onMiscTransmit
Object[] onDialogAbort
Object[] onSubChange
Object[] onResize
Object[] onStockTransmit
Object[] field2689

**Comment by ThatGamerBlue** [comment]
Superseded by 37c66bb64aebdaa34f4f7448e5f6dd01ec255389

**Pull request closed without merging**
