### PR TITLE
PlayerScouter: Add ability to scout based on total value of gear 

### PR DESCRIPTION
**Pull request by RaidanAlyssi**
Can now put in a minimum value of gear for the player to be scouted, and outputs it in discord.

### CODE REVIEW

**Comment by xKylee** [comment]
@RaidanAlyssi the way this gets the value is completely wrong, i would suggest looking at how equipment inspector gathers the total gear value for a more accurate representation

**Comment by RaidanAlyssi** [comment]
> 
> 
> @RaidanAlyssi the way this gets the value is completely wrong, i would suggest looking at how equipment inspector gathers the total gear value for a more accurate representation

I will take a look soon.

**Comment by jjfishbeck44** [comment]
For wilderness scouting, I suggest that the main thing pkers are looking for while Looking at the discord data, isn’t the total risked gp, but they are focusing on what weapon these players are wielding, their prayer level, and if they skulled/or not. Things like displaying the prayer level would be a great tool, and also their rsns, and amount players they are with. 
Cuz with using the equipment inspector The value may be low on paper but it’s obviously that a player wearing a dinns with 98 prayer at wildly alter has noted bones on him. Or that a person with crawbow, chainmace at revs has 250k in ether alone + loot.

**Comment by xKylee** [comment]
> > @RaidanAlyssi the way this gets the value is completely wrong, i would suggest looking at how equipment inspector gathers the total gear value for a more accurate representation
> 
> I will take a look soon.

how did you get on?

**Comment by RaidanAlyssi** [comment]
> 
> 
> > > @RaidanAlyssi the way this gets the value is completely wrong, i would suggest looking at how equipment inspector gathers the total gear value for a more accurate representation
> > 
> > 
> > I will take a look soon.
> 
> how did you get on?

I haven't gotten to it yet.

**Pull request closed without merging**
