### PR TITLE
mixins: fix null safety error

### PR DESCRIPTION
**Pull request by ThatGamerBlue**
more like a stonewall safety error
please dont delete the fucking repo again

### CODE REVIEW

**Comment by ThatGamerBlue** [comment]
oh yeah this is untested but it should work lol

**Comment by Dogyyblue** [comment]
<3

**Comment by ThatGamerBlue** [comment]
yeah it totally just crashes

**Comment by ThatGamerBlue** [comment]
bugs fixed in the injector will reopen and update later

**Pull request closed without merging**
