### PR TITLE
stonedloottracker: correctly read JSON

### PR DESCRIPTION
**Pull request by tha23rd**
Currently Stoned Loot Tracker will not read minified json, which some of the logs appear to be in. This PR fixes that so that both pretty printed and minified json can be correctly read.

### CODE REVIEW

**Comment by Lucwousin** [comment]
Oh no, can you rework this entire class to use ` JsonReader` ? It's pretty much exactly what it needs

**Comment by tha23rd** [comment]
So the loot files are not actually valid JSON... Which makes using JSONReader to read the files in a backwards compatible manner pretty difficult. 

Here is an example loot file that contains both minified and pretty printed JSON (note the lack of a high level json array structure).

https://gist.github.com/tha23rd/b404a9a4e9e58ee56e9f5e1cb8a55258

**Comment by Lucwousin** [comment]
I feel like it would be easier to fix that rather than writing a new parser :P

I think there's even options to be lenient with top level classes, and even if not, just a quick regex looking for ` \}\n\{` and replacing with `},{` and plopping a `[` and a `]` before/behind the string would fix it

I'll merge it and create a issue

**Comment by Owain94** [comment]
When we updated google GSON this bug got introduced. Their old version allowed non valid json to be outputted and ingested, the new version however fixed this.

Because of that I added this dirty fix that allows ingesting the non valid json.

Converting it to valid json and appendix new loot to it creates the same problem we had with the local persistent loot tracker where it would lag badly because it has to ingest the json, append a new block and output it.

Reworking the plugin to work with the loottracker database is the best option imo but I’m not at all sure if the database is even used when local persistence is turned off in the loottracker. That’s easy to lookup though.

All data from stoned loot tracker has to be added to the database which will have to be deduplicated with local loottracker data that’s already present in the database in an ideal world (which might be impossible).

**Comment by Ganom** [comment]
> 
> 
> When we updated google GSON this bug got introduced. Their old version allowed non valid json to be outputted and ingested, the new version however fixed this.
> 
> Because of that I added this dirty fix that allows ingesting the non valid json.
> 
> Converting it to valid json and append new loot to it creates the same problem we had with the local persistent loot tracker where it would lag badly because it has to ingest the json, append a new block and output it.
> 
> Reworking the plugin to work with the loottracker database is the best option imo but I’m not at all sure if the database is even used when local persistence is turned off in the loottracker. That’s easy to lookup though.
> 
> All data from stoned loot tracker has to be added to the database which will have to be deduplicated with local loottracker data that’s already present in the database in an ideal world (which might be impossible).

You should update the issue https://github.com/open-osrs/runelite/issues/1833 with this information.

**Pull request merged**
