### PR TITLE
client: Remove (harmless) data submission api calls to openosrs.dev

### PR DESCRIPTION
**Pull request by swazrgb**
Removes all references to openosrs.dev except for sessions. I chose to keep sessions since they might provide valuable information for the homepage, and do not submit any information at all other than the fact that a client is running.

Also switches the reference to repo.runelite.net as per https://github.com/runelite/runelite/blob/10b502278e8071504a438144e11e4770bd224c24/pom.xml#L92

### CODE REVIEW

**Comment by zeruth** [comment]
animations and xteas will stay. sounds was the only thing removed.

**Comment by ThatGamerBlue** [comment]
animations and xteas are broken anyway

**Comment by zeruth** [comment]
how so? animations.openosrs.dev/get works just fine.

maybe fix instead of removing then?

**Comment by ThatGamerBlue** [comment]
submission is broken, and we claim to send no data back to our servers which is one of our major points, we should actually be truthful about that

**Comment by zeruth** [comment]
image
no it isnt, as i just verified. We collect xtea keys and animations, thats not user data, thats server data.

**Comment by swazrgb** [comment]
For what it's worth, this came up due to a discussion in discord where the developers stated that they "do not send any data to their servers". This was incorrect, as some data was sent to their servers.

So I proposed they either amend this statement, or we make the client truly not submit any data.

Personally I would be fine with reverting this PR & restoring this functionality, as long it isn't glossed over when claiming that absolutely no data is sent. Amending that statement to saying that no personal data is sent would probably be enough.

**Comment by joshuataylor** [comment]
Maybe opt-in would be the best way forward, with explanations how it helps?

**Comment by zeruth** [comment]
virtually no-one would opt-in, making the data collection useless. The animations are probably mostly complete anyways so any that are missing should be easy to get. I don't really feel like defending my shit anymore and nobody else here really cares about rsps support so it can stay gone.

**Pull request merged**
