### PR TITLE
checkstyle: fix automated Checkstyle using Checkstyle-IDEA

### PR DESCRIPTION
**Pull request by IanWONeill**
also removed unused import in RSBufferMixin to pass checkstyle.xml

### CODE REVIEW

**Comment by IanWONeill** [comment]
fuck it.

**Comment by IanWONeill** [comment]
https://streamable.com/z4j6m

**Comment by Lucwousin** [comment]
This is what I get when I try importing it

````
com.puppycrawl.tools.checkstyle.api.CheckstyleException: SuppressionCommentFilter is not allowed as a child in Checker
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:497)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:61)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:26)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:60)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:51)
	at org.infernus.idea.checkstyle.checker.CheckerFactoryWorker.run(CheckerFactoryWorker.java:46)

**Comment by Owain94** [comment]
Instead of doing this we should update the gradle checkstyle plugin so the ide plugin and the gradle plugins versions match and can use the same config without any errors

**Comment by IanWONeill** [comment]
> This is what I get when I try importing it
> 
> ```
> com.puppycrawl.tools.checkstyle.api.CheckstyleException: SuppressionCommentFilter is not allowed as a child in Checker
> 	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:497)
> 	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
> 	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:61)
> 	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:26)
> 	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)
> 	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:60)
> 	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:51)
> 	at org.infernus.idea.checkstyle.checker.CheckerFactoryWorker.run(CheckerFactoryWorker.java:46)
> ```

https://github.com/open-osrs/runelite/pull/1866/commits/1ac019bcac2176558cceffaa42e7de79edf3baa3 

Should fix it by placing it below TreeRunner module, this was the error from before doing this afaik.

**Comment by Lucwousin** [comment]
No, I checked out your branch and tried the configuration in this pr. I didn't change anything. This doesn't work (for me)

**Comment by Lucwousin** [comment]
I think it didn't work because the doctype wasn't imported. After doing that it worked immediately (for a while already; I just forgot this issue existed)

**Pull request closed without merging**
