### PR TITLE
loottracker: Fix PvP kill msg value

### PR DESCRIPTION
**Pull request by stone-wall**
Made this edit via the github website so not able to test atm and i take no responsibility if it breaks everything

### CODE REVIEW

**Comment by stone-wall** [comment]
🗡 🗡 🗡 🗡 🗡 🗡 🗡 🗡 🗡 🗡

**Comment by xKylee** [comment]
does not work hombre

**Comment by xKylee** [comment]
still broken hombre

**Comment by xKylee** [comment]
will need to RE-PR to https://github.com/open-osrs/plugins.

**Pull request closed without merging**
