### PR TITLE
client: make actions follow menu entry params.

### PR DESCRIPTION
**Pull request by Ganom**

### CODE REVIEW

**Comment by ThatGamerBlue** [comment]
keep canvasX and Y

**Comment by Ganom** [comment]
> keep canvasX and Y

Is there a reason why? It's not used for anything.

**Comment by ThatGamerBlue** [comment]
its different in the two invokes, and the client does use it

**Comment by redeems** [comment]
@ThatGamerBlue this looks good to me, it's used in the client, however..it's not being changed in a way that will effect that. The only thing that's changed is how it's implemented on a runelite api level.

**Comment by ThatGamerBlue** [comment]
can we keep the old one but change it to add a chat message to the chatbox saying this is deprecated and will be removed on xx/xx/xxxx then do the action, i really dont want to deal with hundreds of morons in support complaining their client crashes with their unethical gamer plugins

**Pull request merged**
