### PR TITLE
mes: make ShopComparableEntry use standardized string.

### PR DESCRIPTION
**Pull request by Ganom**

### CODE REVIEW

**Comment by Lucwousin** [comment]
This won't help, the reason it doesn't work is because left clicking will turn `Buy 10, Coconut` into `Buy 10, Buy 10`

**Comment by Ganom** [comment]
> This won't help, the reason it doesn't work is because left clicking will turn `Buy 10, Coconut` into `Buy 10, Buy 10`

I tested it, and this solved the issue for me.

**Comment by xKylee** [comment]
quickly testing, will confirm.

**Comment by xKylee** [comment]
yup, tested with 10 items and works fine

**Pull request merged**
