### PR TITLE
thistitlemakesthebothappy: replace the client with something better

### PR DESCRIPTION
**Pull request by ThatGamerBlue**

### CODE REVIEW

**Comment by SRLJustin** [comment]
LGTM

**Comment by JumpIfZero** [comment]
Would love to see hiscores getting implemented for this

**Comment by ThatGamerBlue** [comment]
@SRLJustin re-review pls <3

**Comment by buracc** [comment]
lgtm

**Comment by Sundar-Gandu** [comment]
Does this work on GNU/Linux?

**Comment by ThatGamerBlue** [comment]
> Does this work on GNU/Linux?

templeos only

**Comment by Ganom** [comment]
LGTM

**Review by Ganom — APPROVED** [review]

**Pull request merged**
