### PR TITLE
WorldLocation: Major expansion

### PR DESCRIPTION
**Pull request by Macweese**
## Major changes

- Added over 500 new locations.
Some locations were merged together, others split further into finer segments.

- Removed few locations.
Locations that no longer exist such as Clan Wars or other misguiding locations have been appropriately corrected or replaced.

- Renamed field display labels to give a more intuitive description of the intended world point.<br> Example <br>Old → `SANDCRAB("Sandcrabs", new Location(1706, 3475, 1730, 3455), 0)`<br>New → `SANDCRABS_BANK("Sandcrabs Bank", new Location(1706, 3475, 1730, 3455), 0)`

- Renamed and organised fields.
Fields sorted alphabetically by main regions then sub-categorised alphabetically _again_ by their sub-regions or notable features with an index (comment) preceding each block category, for a quick glance of what areas are included.

## Minor changes

- Limited `distanceTo(worldPoint)` to 128 squares (region length * 2) from 10000 (???:D) to prevent mislabeling areas and confusion, particularly in instances.<br>This could be reduced even further but might create gaps in sparsely distributed regions such as Great Kourend or the desert.

## Other changes

- Fixed error which caused each world area to be placed on wrong coordinates along y-axis.

- Added <code>Math.abs(Coord - Coord<sub>1</sub>)</code> to get absolute value when calculating polygon dimensions from coordinates.

- Spelling corrections

---
### Notes
With these changes there should now be almost¹ no "blind-spots" on the RuneScape surface world, meaning you should always have some location attached to your player. Additionally, many instances have had labels added to them, specifically popular locations such as caves, dungeons, etc.
However, not all possible ones were added e.g. places such as "Fight Caves",  "The Inferno", "Hallowed Sepulchre" and Runecraft Altars (upon entering). This was a deliberate choice, more can always be added. 

¹The exceptions are; 
• Lithkren Island
• Trollweiss Mountain (snow sled area)
• Ice Path
• Fremennik Basilisk Knight Island (surface)
• POH

The issue of world areas being interpreted wrong and therefore displaying disorienting information was fixed. Compartmentalisation of areas such as splitting Grand Exchange into quadrants is no longer needed.

When adding new locations entering coordinates must be done with regards to their points relative to origin on the Cartesian plane.
##### Example
<code>LOCATION("Name of Location", new Location(X<sub>1</sub>, Y<sub>1</sub>, X<sub>2</sub>, Y<sub>2</sub>), Z)</code>

##### Where the following must apply:<br>X<sub>1</sub> < X<sub>2</sub><br>Y<sub>1</sub> > Y<sub>2</sub>
This is because it will create the polygon from the coordinate closest to the origin and then add the dimensions derived from<br><code>Width |X| = X<sub>1</sub> - X<sub>2</sub></code> & <code>Height |Y| = Y<sub>1</sub> - Y<sub>2</sub></code> for the end coordinate.

### CODE REVIEW

**Comment by Macweese** [comment]
## Commit: WorldLocation: Fields hierarchy
#### Summary
After some testing I found that a niche issue arises from the combination of the alphabetical sorting and the for loop. This aims to band-aid the issue as best possible until proper rework is done.

----
### Changes

Renamed fields

Appended main areas (BB) which house other locations with `_ZONE` .

Example
Old → `HOSIDIUS("Hosidius", new Location(1737, 3627, 1789, 3582), 0),`
New → `HOSIDIUS_ZONE("Hosidius", new Location(1737, 3627, 1789, 3582), 0),`

Reason for this is to solve a problem with the `for loop` responsible for iterating over all locations to find which one the player is located in.
Since they are sorted alphabetically, `HOSIDIUS` comes before `HOSIDIUS_BANK` or any other location prefixed with "hosidius". 
Disregarding if  `worldArea ∈ BB`.

So, coincidentally, appending BB areas with `_ZONE` is just a lucky "solution" as a result of the alphabetical sorting to push the area down in the hierarchy.

To be clear; This is a hack, not a proper solution.
Ideally, in a perfect world the entire thing would be replaced by a proper R-Tree or other spatial access method.
However, for now, this is as good as it gets seeing as it'd be a pretty big task.

**Review by Ganom — DISMISSED** [review]
LGTM, nice work.

As for zones and then sub-zones, you could abstract it as such, but as you said, that'd likely be a bit more effort.

**Comment by Macweese** [comment]
### Commit: Sort coordinates

This has been in the back of mind and it's been bugging me.

**Comment by xKylee** [comment]
LGTM @ThatGamerBlue can you cast your eyes over this pls.

**Review by xKylee — APPROVED** [review]

**Comment by ThatGamerBlue** [comment]
> LGTM @ThatGamerBlue can you cast your eyes over this pls.

no i cant

**Review by zeruth — APPROVED** [review]

**Pull request merged**
