### PR TITLE
client: don't crash if we can't create a local socket

### PR DESCRIPTION
**Pull request by ThatGamerBlue**

### CODE REVIEW

**Review by Owain94 — APPROVED** [review]
LGTM

**Comment by f0rmatme** [comment]
Tested this, still crashes on my end.

**Comment by f0rmatme** [comment]
No longer crashes the client
Client still has the error, not sure if it matters?

`2021-05-25T07:22:36.476-0700 [QUIET] [system.out] java.net.SocketException: error setting options
2021-05-25T07:22:36.476-0700 [QUIET] [system.out] 	at java.base/java.net.TwoStacksPlainDatagramSocketImpl.join(Native Method)
2021-05-25T07:22:36.476-0700 [QUIET] [system.out] 	at java.base/java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:216)
2021-05-25T07:22:36.476-0700 [QUIET] [system.out] 	at java.base/java.net.MulticastSocket.joinGroup(MulticastSocket.java:328)
2021-05-25T07:22:36.476-0700 [QUIET] [system.out] 	at org.jgroups.protocols.UDP.createSockets(UDP.java:449)
2021-05-25T07:22:36.476-0700 [QUIET] [system.out] 	at org.jgroups.protocols.UDP.start(UDP.java:324)
2021-05-25T07:22:36.476-0700 [QUIET] [system.out] 	at org.jgroups.stack.ProtocolStack.startStack(ProtocolStack.java:878)
2021-05-25T07:22:36.476-0700 [QUIET] [system.out] 	at org.jgroups.JChannel.startStack(JChannel.java:942)
2021-05-25T07:22:36.476-0700 [QUIET] [system.out] 	at org.jgroups.JChannel._preConnect(JChannel.java:812)
2021-05-25T07:22:36.476-0700 [QUIET] [system.out] 	at org.jgroups.JChannel.connect(JChannel.java:332)
2021-05-25T07:22:36.476-0700 [QUIET] [system.out] 	at org.jgroups.JChannel.connect(JChannel.java:326)
2021-05-25T07:22:36.476-0700 [QUIET] [system.out] 	at com.openosrs.client.util.Groups.init(Groups.java:62)
2021-05-25T07:22:36.476-0700 [QUIET] [system.out] 	at net.runelite.client.plugins.OPRSExternalPluginManager.setupInstance(OPRSExternalPluginManager.java:138)
2021-05-25T07:22:36.476-0700 [QUIET] [system.out] 	at net.runelite.client.RuneLite.start(RuneLite.java:350)
2021-05-25T07:22:36.476-0700 [QUIET] [system.out] 	at net.runelite.client.RuneLite.main(RuneLite.java:307)`

**Review by Owain94 — APPROVED** [review]
LGTM, can't reproduce the error to test this out, but the code looks good

**Pull request merged**
